INSERT INTO TBL_HISTORY(USER_PKID, KEYWORD_NM, REG_DATE) VALUES(1, '음식', CURRENT_TIMESTAMP());
INSERT INTO TBL_HISTORY(USER_PKID, KEYWORD_NM, REG_DATE) VALUES(1, '고기', CURRENT_TIMESTAMP());
INSERT INTO TBL_HISTORY(USER_PKID, KEYWORD_NM, REG_DATE) VALUES(2, '음식', CURRENT_TIMESTAMP());
INSERT INTO TBL_HISTORY(USER_PKID, KEYWORD_NM, REG_DATE) VALUES(2, '갈비', CURRENT_TIMESTAMP());
INSERT INTO TBL_HISTORY(USER_PKID, KEYWORD_NM, REG_DATE) VALUES(2, '맛집', CURRENT_TIMESTAMP());
INSERT INTO TBL_HISTORY(USER_PKID, KEYWORD_NM, REG_DATE) VALUES(2, '카카오', CURRENT_TIMESTAMP());
INSERT INTO TBL_HISTORY(USER_PKID, KEYWORD_NM, REG_DATE) VALUES(3, '음식', CURRENT_TIMESTAMP());
INSERT INTO TBL_HISTORY(USER_PKID, KEYWORD_NM, REG_DATE) VALUES(3, '자동차', CURRENT_TIMESTAMP());
INSERT INTO TBL_HISTORY(USER_PKID, KEYWORD_NM, REG_DATE) VALUES(3, '호수공원', CURRENT_TIMESTAMP());
INSERT INTO TBL_HISTORY(USER_PKID, KEYWORD_NM, REG_DATE) VALUES(3, '맛집', CURRENT_TIMESTAMP());

INSERT INTO TBL_KEYWORD(KEYWORD_NM, KEYWORD_CNT) VALUES('음식', 3);
INSERT INTO TBL_KEYWORD(KEYWORD_NM, KEYWORD_CNT) VALUES('고기', 1);
INSERT INTO TBL_KEYWORD(KEYWORD_NM, KEYWORD_CNT) VALUES('갈비', 1);
INSERT INTO TBL_KEYWORD(KEYWORD_NM, KEYWORD_CNT) VALUES('맛집', 1);
INSERT INTO TBL_KEYWORD(KEYWORD_NM, KEYWORD_CNT) VALUES('카카오', 1);
INSERT INTO TBL_KEYWORD(KEYWORD_NM, KEYWORD_CNT) VALUES('자동차', 1);
INSERT INTO TBL_KEYWORD(KEYWORD_NM, KEYWORD_CNT) VALUES('호수공원', 1);